export const fakeMRCTitles = [
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
  "這是康健雜誌的MRC範例標題 這是康健雜誌的MRC範例標題",
]

export const fakeSentimentalTitles = [
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
  "這是Sentimental範例標題 這是Sentimental範例標題",
]